# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "nfs_srv" do |nfs_srv|
    nfs_srv.vm.box = "centos/7"
    nfs_srv.vm.box_check_update = false
    nfs_srv.vm.network "private_network", ip: "192.168.51.5", virtualbox__intnet: "sw0"
    nfs_srv.vm.hostname = "srv"
    nfs_srv.vm.provider "virtualbox" do |vb|
    vb.name = "nfs_srv"
    vb.cpus = 1
    vb.memory = "512"
  end
    nfs_srv.vm.provision "shell", path: "server_script.sh"
  end

  config.vm.define "nfs_client" do |nfs_cl1|
    nfs_cl1.vm.box = "centos/7"
    nfs_cl1.vm.box_check_update = false
    nfs_cl1.vm.network "private_network", ip: "192.168.51.10", virtualbox__intnet: "sw0"
    nfs_cl1.vm.hostname = "client"
    nfs_cl1.vm.provider "virtualbox" do |vb|
    vb.name = "nfs_client"
    vb.cpus = 1
    vb.memory = "512"
  end
    nfs_cl1.vm.provision "shell", path: "client_script.sh"
  end

end