---
- name: configure rsyslog server
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^#({{ item.config }}.*)'
    line: '\1'
    backrefs: yes
  loop:
    - { config: '\$ModLoad imudp' }
    - { config: '\$UDPServerRun 514' }
  notify: restart rsyslog
...
